// Code generated by the atomctl ; DO NOT EDIT.
// Code generated by the atomctl ; DO NOT EDIT.
// Code generated by the atomctl ; DO NOT EDIT.
package models

import (
	"database/sql"
)

var db *sql.DB
{{- range . }}
var {{.PascalTable}} *{{.CamelTable}}Model
{{- end }}

// @provider(model)
type models struct {
	db *sql.DB

{{- range . }}
	{{.CamelTable}} *{{.CamelTable}}Model
{{- end }}
}

func (m *models) Prepare() error {
	db = m.db
{{- range . }}
	{{.PascalTable}} = m.{{.CamelTable}}
{{- end }}
	return nil
}
