// Code generated by the atomctl ; DO NOT EDIT.
// Code generated by the atomctl ; DO NOT EDIT.
// Code generated by the atomctl ; DO NOT EDIT.
package models

{{- range . }}
var {{.PascalTable}} *{{.CamelTable}}Model
{{- end }}

// @provider(model)
type models struct {
{{- range . }}
	{{.CamelTable}} *{{.CamelTable}}Model
{{- end }}
}

func (m *models) Prepare() error {
{{- range . }}
	{{.PascalTable}} = m.{{.CamelTable}}
{{- end }}
	return nil
}
