package tests

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

import (
	"time"

	"test/common"
	"test/common/consts"

	"github.com/lib/pq"
	"gorm.io/datatypes"
	"gorm.io/gorm"
	"gorm.io/gorm/schema"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	Statuses  pq.StringArray          `gorm:"column:lcassword;type:text" json:"passwo"`
}

func (*User) TableName(namer schema.Namer) string {
	if namer == nil {
		return TableNameUser
	}
	return namer.TableName(TableNameUser)
}


// Create a new item
//
//	@Summary		create new item
//	@Description	create new item
//	@Tags			TODO_ADD_TAGNAME
//	@Accept			json
//	@Produce		json
//	@Param			a	path		string	true	"A"
//	@Param			accountId	path		int	true	"AccountId"
//	@Param			body	body		dto.KubeImageForm	true	"KubeImageForm"
//	@Success		200		{string}	KubeImageID
//	@Router			/clusters/{a}/b/{accountId} [post]
func Hello(ctx context.Context, a, b int, c *string) (*StructType, error) {
	return &StructType{
		ctx:  ctx,
		Name: "hello",
		Age:  &a,
	}, nil
}
