// Code generated by the atomctl; DO NOT EDIT.

package routes

import (
	 "strings"

	"a/common"

	"github.com/gofiber/fiber/v2"
	. "github.com/rogeecn/fen"
)

func routeUserController(engine fiber.Router, controller *controller.UserController) {
	groupPrefix := "/"+strings.TrimLeft(engine.(*fiber.Group).Prefix,"/")
	engine.Get(strings.TrimPrefix("/users/:id<int>", groupPrefix), DataFunc1(controller.Show, Integer[uint64]("id", PathParamError)))
	engine.Get(strings.TrimPrefix("/users", groupPrefix), DataFunc3(controller.List, Query[UserListQueryFilter](QueryParamError), Query[common.PageQueryFilter](QueryParamError), Query[common.SortQueryFilter](QueryParamError)))
	engine.Post(strings.TrimPrefix("/users", groupPrefix), Func1(controller.Create, Body[UserForm](BodyParamError)))
	engine.Put(strings.TrimPrefix("/users/:id<int>", groupPrefix), Func2(controller.Update, Integer[uint64]("id", PathParamError), Body[UserForm](BodyParamError)))
	engine.Delete(strings.TrimPrefix("/users/:id<int>", groupPrefix), Func1(controller.Delete, Integer[uint64]("id", PathParamError)))
}
