package cmd

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/iancoleman/strcase"
	"github.com/pkg/errors"
	"github.com/rogeecn/atomctl/utils"
	"github.com/samber/lo"
	"github.com/spf13/cobra"
)

// routesCmd represents the routes command
var genRoutesCmd = &cobra.Command{
	Use:   "routes",
	Short: "generate file/project routes",
	RunE:  genRoutes,
}

func init() {
	genCmd.AddCommand(genRoutesCmd)
}

func genRoutes(cmd *cobra.Command, args []string) error {
	var err error
	var path string
	if len(args) == 0 {
		path, err = os.Getwd()
		if err != nil {
			return err
		}
	} else {
		path = args[0]
	}

	path, _ = filepath.Abs(path)
	log.Println("route path: ", path)
	log.Println("go mod package: ", getPackage())

	routes := []RoueDefinition{}
	// if path is file, then get the dir
	if utils.IsFile(path) && strings.HasSuffix(path, ".go") && strings.HasSuffix(filepath.Dir(path), "/controller") {
		log.Println("generate routes for file")
		routes = append(routes, astParseRoutes(path)...)
	} else {
		log.Println("generate routes for dir")

		modulePath := filepath.Join(path, "modules")
		if _, err := os.Stat(modulePath); os.IsNotExist(err) {
			log.Fatal("modules dir not exist, ", modulePath)
		}

		// routePath := filepath.Join(path, "routes")
		// controllerPath := filepath.Join(path, "controller")

		// travel controller to find all controller objects
		filepath.WalkDir(modulePath, func(path string, d fs.DirEntry, err error) error {
			if d.IsDir() {
				return nil
			}
			if !strings.HasSuffix(filepath.Dir(path), "/controller") {
				return nil
			}
			if !strings.HasSuffix(path, ".go") {
				return nil
			}

			routes = append(routes, astParseRoutes(path)...)
			return nil
		})
	}

	// generate files
	for _, route := range routes {
		filename := "route_" + strcase.ToSnake(route.Name) + ".go"
		routePath := filepath.Join(filepath.Dir(filepath.Dir(route.Path)), "routes", filename)

		funcName := fmt.Sprintf(`route%s(group, %s)`, route.Name, strcase.ToLowerCamel(route.Name))
		log.Printf("generate route: %s @ %s\n", routePath, funcName)

		if len(route.Actions) == 0 {
			continue
		}

		routeFilePath := filepath.Join(filepath.Dir(filepath.Dir(route.Path)), "routes/routes.go")
		controllerPkg := fmt.Sprintf(`"%s/controller"`, getPackageRoute(getPackage(), route.Path))
		controllerParam := fmt.Sprintf(`%s *controller.%s`, strcase.ToLowerCamel(route.Name), route.Name)

		// 生成路由方法
		routeContent, err := os.ReadFile(routeFilePath)
		if err != nil {
			log.Printf("[Warn] route provider not exists, %s", routeFilePath)
			continue
		}
		content := string(routeContent)
		// 注入注册方法
		if !strings.Contains(content, funcName) {
			content = strings.Replace(content, "return nil", fmt.Sprintf("%s\n\treturn nil", funcName), 1)
		}
		// 注入参数
		if !strings.Contains(content, controllerParam) {
			content = strings.Replace(content, "(svc contracts.HttpService", fmt.Sprintf("(svc contracts.HttpService, %s", controllerParam), 1)
		}
		// 注入包
		if !strings.Contains(content, controllerPkg) {
			content = strings.Replace(content, "import (", fmt.Sprintf("import (\t\t%s", controllerPkg), 1)
		}
		if err := os.WriteFile(routeFilePath, []byte(content), os.ModePerm); err != nil {
			log.Printf("[Warn] write route provider failed, %s", routeFilePath)
			continue
		}
		_ = exec.Command("go", "fmt", routeFilePath).Run()

		// 生成路由文件
		f, err := os.OpenFile(routePath, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o644)
		if err != nil {
			continue
		}
		defer f.Close()

		_, _ = f.WriteString("// Code generated by the atomctl; DO NOT EDIT.\n\n")
		_, _ = f.WriteString("package routes\n\n")
		_, _ = f.WriteString("import (\n")
		_, _ = f.WriteString("\t \"strings\"\n\n")
		_, _ = f.WriteString(fmt.Sprintf("\t%s\n", controllerPkg))
		for _, im := range route.Imports {
			_, _ = f.WriteString(fmt.Sprintf("\t%s\n", im))
		}
		_, _ = f.WriteString("\n")
		_, _ = f.WriteString("\t\"github.com/gofiber/fiber/v2\"\n")
		_, _ = f.WriteString("\t. \"github.com/rogeecn/fen\"\n")
		_, _ = f.WriteString(")\n\n")

		//
		_, _ = f.WriteString("func route" + route.Name + "(engine fiber.Router, controller *controller." + route.Name + ") {\n")

		_, _ = f.WriteString("\tbasePath := \"/\"+engine.(*fiber.Group).Prefix\n")
		for _, action := range route.Actions {
			_, _ = f.WriteString("\t")
			_, _ = f.WriteString(fmt.Sprintf(`engine.%s(strings.TrimPrefix(%q, basePath), `, strcase.ToCamel(strings.ToLower(action.Method)), formatRoute(action.Route)))

			if action.HasData {
				_, _ = f.WriteString("Data")
			}
			_, _ = f.WriteString("Func")

			paramsSize := len(action.Params)
			if paramsSize >= 1 {
				_, _ = f.WriteString(fmt.Sprintf("%d", paramsSize))
			}

			paramsStrings := []string{"controller." + action.Name}
			for _, p := range action.Params {
				var paramString string
				switch p.Position {
				case PositionPath:
					switch p.Type {
					case "string":
						paramString = fmt.Sprintf(`String(%q, PathParamError)`, p.Name)
					case "int", "uint", "int32", "uint32", "int64", "uint64":
						paramString = fmt.Sprintf(`Integer[%s](%q, PathParamError)`, p.Type, p.Name)
					default:
						log.Panic("invalid path param type: ", p.Type)
					}
				case PositionQuery:
					paramString = fmt.Sprintf(`Query[%s](QueryParamError)`, p.Type)
				case PositionBody:
					paramString = fmt.Sprintf(`Body[%s](BodyParamError)`, p.Type)
				case PositionHeader:
					paramString = fmt.Sprintf(`Header[%s](HeaderParamError)`, p.Type)
				}

				paramsStrings = append(paramsStrings, paramString)
			}
			_, _ = f.WriteString("(" + strings.Join(paramsStrings, ", ") + ")")

			_, _ = f.WriteString(")\n")
		}

		_, _ = f.WriteString("}\n")
	}
	return nil
}

type RoueDefinition struct {
	Path    string
	Name    string
	Imports []string
	Actions []ActionDefinition
}

type ParamDefinition struct {
	Name     string
	Type     string
	Position Position
}

type ActionDefinition struct {
	Route   string
	Method  string
	Name    string
	HasData bool
	Params  []ParamDefinition
}
type Position string

const (
	PositionPath   Position = "Path"
	PositionQuery  Position = "Query"
	PositionBody   Position = "Body"
	PositionHeader Position = "Header"
)

func astParseRoutes(source string) []RoueDefinition {
	if strings.HasSuffix(source, "_test.go") {
		return []RoueDefinition{}
	}

	if strings.HasSuffix(source, "/provider.go") {
		return []RoueDefinition{}
	}

	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, source, nil, parser.ParseComments)
	if err != nil {
		log.Println("ERR: ", err)
		return nil
	}

	imports := make(map[string]string)
	for _, imp := range node.Imports {
		paths := strings.Split(strings.Trim(imp.Path.Value, "\""), "/")
		name := paths[len(paths)-1]
		pkg := imp.Path.Value
		if imp.Name != nil {
			name = imp.Name.Name
			pkg = fmt.Sprintf("%s %q", name, imp.Path.Value)
		}
		imports[name] = pkg
	}

	routes := make(map[string]RoueDefinition)
	actions := make(map[string][]ActionDefinition)
	usedImports := make(map[string][]string)

	// 再去遍历 struct 的方法去
	for _, decl := range node.Decls {
		decl, ok := decl.(*ast.FuncDecl)
		if !ok {
			continue
		}

		// 普通方法不要
		if decl.Recv == nil {
			continue
		}

		recvType := decl.Recv.List[0].Type.(*ast.StarExpr).X.(*ast.Ident).Name
		if _, ok := routes[recvType]; !ok {
			routes[recvType] = RoueDefinition{
				Name:    recvType,
				Path:    source,
				Actions: []ActionDefinition{},
			}
			actions[recvType] = []ActionDefinition{}
		}

		// Doc 中把 @Router 的定义拿出来， Route 格式为 /user/:id [get] 两部分，表示路径和请求方法
		var path, method string
		var err error
		if decl.Doc != nil {
			for _, line := range decl.Doc.List {
				lineText := strings.TrimSpace(line.Text)
				lineText = strings.TrimLeft(lineText, "/ \t")
				if !strings.HasPrefix(lineText, "@Route") {
					continue
				}

				path, method, err = parseRouteComment(lineText)
				if err != nil {
					log.Fatal(errors.Wrapf(err, "file: %s, action: %s", source, decl.Name.Name))
				}
				break
			}
		}
		if path == "" || method == "" {
			log.Printf("[WARN] failed to get router ,file: %s, action: %s", source, decl.Name.Name)
			continue
		}

		// 拿参数列表去, 忽略 context.Context 参数
		params := []ParamDefinition{}
		for _, param := range decl.Type.Params.List {
			// paramsType, ok := param.Type.(*ast.SelectorExpr)

			var typ string
			switch param.Type.(type) {
			case *ast.Ident:
				typ = param.Type.(*ast.Ident).Name
			case *ast.StarExpr:
				paramsType := param.Type.(*ast.StarExpr)
				switch paramsType.X.(type) {
				case *ast.SelectorExpr:
					X := paramsType.X.(*ast.SelectorExpr)
					typ = fmt.Sprintf("*%s.%s", X.X.(*ast.Ident).Name, X.Sel.Name)
				default:
					typ = fmt.Sprintf("*%s", paramsType.X.(*ast.Ident).Name)
				}
			case *ast.SelectorExpr:
				typ = fmt.Sprintf("%s.%s", param.Type.(*ast.SelectorExpr).X.(*ast.Ident).Name, param.Type.(*ast.SelectorExpr).Sel.Name)
			}

			if strings.HasSuffix(typ, "Context") || strings.HasSuffix(typ, "Ctx") {
				continue
			}
			pkgName := strings.Split(strings.Trim(typ, "*"), ".")
			if len(pkgName) == 2 {
				usedImports[recvType] = append(usedImports[recvType], imports[pkgName[0]])
			}

			position := PositionPath
			if strings.HasSuffix(typ, string(PositionQuery)) || strings.HasSuffix(typ, "QueryFilter") {
				position = PositionQuery
			}
			if strings.HasSuffix(typ, string(PositionBody)) || strings.HasSuffix(typ, "Form") {
				position = PositionBody
			}
			if strings.HasSuffix(typ, string(PositionHeader)) {
				position = PositionHeader
			}
			typ = strings.TrimPrefix(typ, "*")

			for _, name := range param.Names {
				params = append(params, ParamDefinition{
					Name:     name.Name,
					Type:     typ,
					Position: position,
				})
			}
		}

		actions[recvType] = append(actions[recvType], ActionDefinition{
			Route:   path,
			Method:  strings.ToUpper(method),
			Name:    decl.Name.Name,
			HasData: len(decl.Type.Results.List) > 1,
			Params:  params,
		})
	}

	var items []RoueDefinition
	for k, item := range routes {
		a, ok := actions[k]
		if !ok {
			continue
		}
		item.Actions = a
		item.Imports = []string{}
		if im, ok := usedImports[k]; ok {
			item.Imports = lo.Uniq(im)
		}
		items = append(items, item)
	}
	return items
}

func parseRouteComment(line string) (string, string, error) {
	pattern := regexp.MustCompile(`(?mi)@router\s+(.*?)\s+\[(.*?)\]`)
	submatch := pattern.FindStringSubmatch(line)

	if len(submatch) != 3 {
		return "", "", errors.New("invalid route definition")
	}

	return submatch[1], submatch[2], nil
}

func getPackageRoute(mod, path string) string {
	paths := strings.SplitN(path, "modules", 2)
	pkg := paths[1]

	for {
		pkg = filepath.Dir(pkg)
		if strings.HasSuffix(pkg, "controller") {
			return filepath.Join(mod, "modules", filepath.Dir(pkg))
		}

		if len(pkg) <= 1 {
			return ""
		}
	}
}

func formatRoute(route string) string {
	pattern := regexp.MustCompile(`(?mi)\{(.*?)\}`)
	if !pattern.MatchString(route) {
		return route
	}
	return pattern.ReplaceAllString(route, ":$1")
}
